// codegen.cpp - Phase 4: turns the checked AST into Python source code
#include "semantic.cpp"

class CodeGenerator {
    string out;

    string spaces(int indent) { return string(indent * 4, ' '); }

    string expression(ASTNode* node) {
        NumberNode* number = dynamic_cast<NumberNode*>(node);
        if (number != nullptr) return number->value;

        IdentifierNode* id = dynamic_cast<IdentifierNode*>(node);
        if (id != nullptr) return id->name;

        BinaryNode* bin = dynamic_cast<BinaryNode*>(node);
        string op = bin->op;
        // integer division in Python is //
        if (op == "/" && bin->type == INT_TYPE) op = "//";
        return "(" + expression(bin->left) + " " + op + " " + expression(bin->right) + ")";
    }

    // decimal variables are wrapped in float() so 5 is stored as 5.0
    string value(string varType, ASTNode* node) {
        if (varType == DEC_TYPE) return "float(" + expression(node) + ")";
        return expression(node);
    }

    void block(vector<ASTNode*>& statements, int indent) {
        if (statements.empty()) out += spaces(indent) + "pass\n";
        for (ASTNode* s : statements) statement(s, indent);
    }

    void statement(ASTNode* node, int indent) {
        string pad = spaces(indent);

        DeclarationNode* decl = dynamic_cast<DeclarationNode*>(node);
        if (decl != nullptr) {
            out += pad + decl->name + " = " + value(decl->varType, decl->value) + "\n";
            return;
        }

        AssignmentNode* assign = dynamic_cast<AssignmentNode*>(node);
        if (assign != nullptr) {
            out += pad + assign->name + " = " + value(assign->varType, assign->value) + "\n";
            return;
        }

        PrintNode* print = dynamic_cast<PrintNode*>(node);
        if (print != nullptr) {
            out += pad + "print(" + expression(print->expression) + ")\n";
            return;
        }

        IfNode* ifNode = dynamic_cast<IfNode*>(node);
        if (ifNode != nullptr) {
            out += pad + "if " + expression(ifNode->condition) + ":\n";
            block(ifNode->ifBody, indent + 1);
            if (!ifNode->elseBody.empty()) {
                out += pad + "else:\n";
                block(ifNode->elseBody, indent + 1);
            }
            return;
        }

        WhileNode* whileNode = dynamic_cast<WhileNode*>(node);
        if (whileNode != nullptr) {
            out += pad + "while " + expression(whileNode->condition) + ":\n";
            block(whileNode->body, indent + 1);
        }
    }

public:
    string generate(ProgramNode* program) {
        out = "# Generated by the Bangla compiler\n";
        for (ASTNode* s : program->statements) statement(s, 0);
        return out;
    }
};
